name: Sync Fork
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora
  workflow_dispatch: # Permite rodar manualmente se quiser

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync upstream
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/Mateus-SR/La-Casa-De-Sacola
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
